name: Auto Commit HTML

on:
  schedule:
    - cron: '*/1 * * * *'  # jede Minute
  workflow_dispatch:       # manuell auslösbar

jobs:
  commit-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git config
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@example.com"

      - name: Commit only changed HTML files
        run: |
          git add -u '*.html' || true
          git diff --cached --quiet || git commit -m "🔁 Auto-update HTML files"
          git push
